export const GAME_TICK_RATE = 60;
export const DEFAULT_MAX_PLAYERS = 4;
export const TANK_MAX_HEALTH = 100;
export const MAP_WIDTH = 800;
export const MAP_HEIGHT = 600;
export const POWERUP_SPAWN_INTERVAL = 10000;

export const POWERUP_TYPES = {
    HOMING_MISSILE: 'HOMING_MISSILE',
    RAPID_FIRE: 'RAPID_FIRE',
    GHOST_BULLET: 'GHOST_BULLET',
    TURBO_DRIVE: 'TURBO_DRIVE'
};

export const ADVANCED_BULLET_TYPES = {
    AOE_EXPLOSION: 'AOE_EXPLOSION',
    CLUSTER_BOMB: 'CLUSTER_BOMB',
    BOUNCING_BULLET: 'BOUNCING_BULLET'
};